"""tabelas_iniciais_limpas

Revision ID: 873796350237
Revises: 
Create Date: 2026-08-07 17:08:50.908966

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '873796350237'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('audit_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('audit_metadata', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('calendar_channels',
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('canal_google', sa.String(length=250), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('validade_calendario', sa.DateTime(timezone=True), nullable=False),
    sa.Column('renovacao_calendario', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_table('sync_cursors',
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('sync_token', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('calendar_id')
    )
    op.create_table('webhook_receipts',
    sa.Column('webhook_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('dedup_hash', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('webhook_id'),
    sa.UniqueConstraint('dedup_hash')
    )
    op.create_table('calendar_events',
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=True),
    sa.Column('titulo', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar_channels.resource_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('armazena_dados',
    sa.Column('id_save', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.event_id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['calendar_channels.resource_id'], ),
    sa.PrimaryKeyConstraint('id_save')
    )
    op.create_index(op.f('ix_armazena_dados_id_save'), 'armazena_dados', ['id_save'], unique=False)
    op.create_table('contacts',
    sa.Column('contact_id', sa.String(length=255), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.event_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('event_versions',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.event_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('reminder_jobs',
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('policy_code', sa.Text(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.event_id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['calendar_channels.resource_id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('reminder_policies',
    sa.Column('policy_id', sa.String(length=255), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('rules_json', sa.JSON(), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.event_id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['calendar_channels.resource_id'], ),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_table('message_attempts',
    sa.Column('attempt_id', sa.String(length=255), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=True),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('payload_enviado', sa.JSON(), nullable=True),
    sa.Column('resposta_sanitizada', sa.JSON(), nullable=True),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.event_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['reminder_jobs.job_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['event_versions.version_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_attempts')
    op.drop_table('reminder_policies')
    op.drop_table('reminder_jobs')
    op.drop_table('event_versions')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_armazena_dados_id_save'), table_name='armazena_dados')
    op.drop_table('armazena_dados')
    op.drop_table('calendar_events')
    op.drop_table('webhook_receipts')
    op.drop_table('sync_cursors')
    op.drop_table('calendar_channels')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
