"""criacao_tabelas_iniciais

Revision ID: d3a367cd145d
Revises: 
Create Date: 2026-07-31 18:08:47.364004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3a367cd145d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_channels_history')
    op.drop_table('webhook_events_idempotency')
    op.drop_table('sync_cursors')
    op.alter_column('calendar_channels', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('calendar_channels', 'validade_calendario',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('calendar_channels', 'renovacao_calendario',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('calendar_channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('calendar_channels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('calendar_events', 'calendar_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_events', 'calendar_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('calendar_channels', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('calendar_channels', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('calendar_channels', 'renovacao_calendario',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('calendar_channels', 'validade_calendario',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('calendar_channels', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.create_table('sync_cursors',
    sa.Column('calendar_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sync_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('parametros_usados', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cursor_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar_channels.resource_id'], name=op.f('sync_cursors_calendar_id_fkey')),
    sa.PrimaryKeyConstraint('cursor_id', name=op.f('sync_cursors_pkey'))
    )
    op.create_table('webhook_events_idempotency',
    sa.Column('message_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('estado_processamento', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('payload_recebido', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('message_number', name=op.f('webhook_events_idempotency_pkey'))
    )
    op.create_table('calendar_channels_history',
    sa.Column('history_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('acao', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('detalhes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('history_id', name=op.f('calendar_channels_history_pkey'))
    )
    # ### end Alembic commands ###
