"""add provider_message_id

Revision ID: f9963425e319
Revises: 873796350237
Create Date: 2026-08-11 13:39:07.602767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9963425e319'
down_revision: Union[str, Sequence[str], None] = '873796350237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder_jobs', sa.Column('provider_message_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_reminder_jobs_provider_message_id'), 'reminder_jobs', ['provider_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_jobs_provider_message_id'), table_name='reminder_jobs')
    op.drop_column('reminder_jobs', 'provider_message_id')
    # ### end Alembic commands ###
